[package]
name = "neon-wc-demo"
version = "0.1.0"
authors = ["Kenneth Bermudez"]
license = "MIT"
build = "build.rs"

[lib]
name = "neon-wc-demo"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.17"

[dependencies]
neon = "0.1.17"
rayon = "0.8.2"
